trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

# Stage 1
# Build Docker image
# Publish K8S Deployment file
- stage: Build
  displayName: Build Docker image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an Docker image for currency-exchange-devops
      inputs:
        containerRegistry: 'asazanowicz-docker-hub'
        repository: 'asazanowicz/currency-exchange-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifest'
        publishLocation: 'Container'


# Stage 2
# Download K8S Deployment file
# Deploy tp K8S Azure cluster with Docker image asazanowicz/currency-exchange-devops
- stage: Deploy
  displayName: Deploy Docker image to k8stest_dev
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifest'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'azure-k8s-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/deployment.yaml'
        containers: 'asazanowicz/currency-exchange-devops:$(tag)'