trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV2@2
  displayName: Initializing Terraform state
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state-asazanowicz'
    backendAWSKey: 'k8s-dev.tfstate'
- task: TerraformTaskV2@2
  displayName: Creating EKS cluster
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-for-terraform'
# - task: TerraformTaskV2@2
#   displayName: Destroying EKS cluster
#   inputs:
#     provider: 'aws'
#     command: 'destroy'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
#     environmentServiceNameAWS: 'aws-for-terraform'
